Changed use of mongodb_fixtures option
mdomke/humongous pull request #10
Opened 2017-08-30 13:44 UTC by rubenbonilla

* Is not necessary to use mongodb_fixtures option to load data in data base as is said in README configuration section
    * Added tests to verify new changes

2017-11-09 22:36 UTC, zoresvit commented
It took me a while to figure out that current implementation requires `mongodb_fixtures` to load the fixtures even though documentation does not say so. Merging this would make `pytest-mongodb` much more usable and intuitive.

2017-11-09 23:05 UTC, mdomke requested changes

2017-11-09 23:05 UTC, mdomke commented on pytest_mongodb/plugin.py
> +        if selected and supported or supported:
This is essentially the same as writing
```python
if supported:
    ...
```
dropping the possibility to specify specific collections to be loaded. I would say what you actually want is to change line 92 to be
```python
selected = collection in fixtures if fixtures else True
```
because the boolean logic there is flawed. This would also mean that you have to adapt the tests by basically removing the changes that you did.

2017-11-09 23:09 UTC, mdomke commented
@zoresvit It is in fact a bug that collections are not loaded unconditionally if the `mongodb_fixtures`-option is not specified in the config. This pull-request however removes the ability to select only a subset of the collections that reside in your `mongodb_fixture_dir` all together.

2017-11-15 07:45 UTC, ndparker commented
Hi,

I just stumbled over that problem and I fixed it locally (just a manual smoke test) by changing the one line to
```selected = not fixtures or collection in fixtures```

Would you like a different PR for that or can this just be fixed? :-)

Thanks!

2017-11-26 22:05 UTC, rubenbonilla commented on pytest_mongodb/plugin.py
> +        if selected and supported or supported:
Okay, i'm updating the PR doing the change you mentioned above.

But i would like to inlcude a test to check if there is not mongodb_fixture option defined some .yaml or .json file will be loaded,but i don't know how to do it.

2017-11-26 22:59 UTC, merged